
name: android

on: push

# 3 different jobs that run in parallel to check the following
# Detekt: Checks for Kotlin code smells & formatting issues (Ktlint enabled within detekt)
# Lint: Checks for Android code smells
# Tests: Checks for failing Unit tests

# Due to being different jobs they run in independent machines so each requires setup + cache config
# Caching Gradle with key hash of top build gradle, dependencies file or gradle-wrapper change cache

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('buildSrc/src/main/java/Dependencies.kt') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Lint
        run: ./gradlew lintDebug
        
  test2:
    runs-on: ubuntu-latest
    steps: #AndroidTestReportAction parse test result for android test report

      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test # use can use another command to run juni test like: ./gradlew testDebugUnitTest
        continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step

      - name: Make Unit test report
        uses: doanpt/AndroidTestReportAction@v1.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('buildSrc/src/main/java/Dependencies.kt') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
